version: "3.8"

services:
    postgres:
        container_name: postgres
        image: postgres:14.5
        restart: always
        ports:
            - 5433:5432
        environment:
            POSTGRES_PASSWORD: 1234
        networks:
            - databases

networks:
    databases:
        name: databases